export enum EventTag {
  FOOD = 'FOOD',
  TRANSPORT = 'TRANSPORT',
  ENTERTAINMENT = 'ENTERTAINMENT',
  SHOPPING = 'SHOPPING',
  HEALTH = 'HEALTH',
  TRAVEL = 'TRAVEL',
  UTILITIES = 'UTILITIES',
  OTHER = 'OTHER',
}
