// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: geolocation/geolocation.query.proto

/* eslint-disable */

export const protobufPackage = "geolocation";

export interface GetNearbyTransactionsRequest {
  latitude: number;
  longitude: number;
  radiusKm: number;
}

export interface AutocompleteRequest {
  query: string;
}

export const GEOLOCATION_PACKAGE_NAME = "geolocation";
