// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: geolocation/geolocation.query.proto

/* eslint-disable */

export const protobufPackage = "geolocation";

export interface GetNearbyTransactionsRequest {
  latitude: number;
  longitude: number;
  radiusKm: number;
  tag: string;
}

export interface GetMapZonesRequest {
  latitude: number;
  longitude: number;
  radiusKm: number;
}

export interface MapZone {
  id: string;
  latitude: number;
  longitude: number;
  weight: number;
  radius: number;
  tag: string;
}

export interface GetMapZonesResponse {
  zones: MapZone[];
}

export const GEOLOCATION_PACKAGE_NAME = "geolocation";
