// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: geolocation/geolocation.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { TrackTransactionRequest } from "./geolocation.command.pb.js";
import { AutocompleteRequest, GetNearbyTransactionsRequest } from "./geolocation.query.pb.js";
import {
  AutocompleteResponse,
  GetNearbyTransactionsResponse,
  TrackTransactionResponse,
} from "./geolocation.responses.pb.js";

export const protobufPackage = "geolocation";

export const GEOLOCATION_PACKAGE_NAME = "geolocation";

export interface GeolocationServiceClient {
  trackTransaction(request: TrackTransactionRequest): Observable<TrackTransactionResponse>;

  getNearbyTransactions(request: GetNearbyTransactionsRequest): Observable<GetNearbyTransactionsResponse>;

  autocomplete(request: AutocompleteRequest): Observable<AutocompleteResponse>;
}

export interface GeolocationServiceController {
  trackTransaction(
    request: TrackTransactionRequest,
  ): Promise<TrackTransactionResponse> | Observable<TrackTransactionResponse> | TrackTransactionResponse;

  getNearbyTransactions(
    request: GetNearbyTransactionsRequest,
  ): Promise<GetNearbyTransactionsResponse> | Observable<GetNearbyTransactionsResponse> | GetNearbyTransactionsResponse;

  autocomplete(
    request: AutocompleteRequest,
  ): Promise<AutocompleteResponse> | Observable<AutocompleteResponse> | AutocompleteResponse;
}

export function GeolocationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["trackTransaction", "getNearbyTransactions", "autocomplete"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("GeolocationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("GeolocationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const GEOLOCATION_SERVICE_NAME = "GeolocationService";
