// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: geolocation/geolocation.proto

/* eslint-disable */

export const protobufPackage = "geolocation";

export interface Coordinate {
  latitude: number;
  longitude: number;
}

export interface TransactionPoint {
  transactionId: string;
  latitude: number;
  longitude: number;
  amount: number;
}

export const GEOLOCATION_PACKAGE_NAME = "geolocation";
