// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: geolocation/geolocation.responses.proto

/* eslint-disable */
import { TransactionPoint } from "./geolocation.pb.js";

export const protobufPackage = "geolocation";

export interface TrackTransactionResponse {
  success: boolean;
  message: string;
  latitude: number;
  longitude: number;
}

export interface GetNearbyTransactionsResponse {
  transactions: TransactionPoint[];
}

export interface AutocompleteResponse {
  suggestions: string[];
}

export const GEOLOCATION_PACKAGE_NAME = "geolocation";
