// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: file/file.responses.proto

/* eslint-disable */
import { File } from "./file.pb.js";

export const protobufPackage = "file";

export interface FileResponse {
  file: File | undefined;
}

export interface FileListResponse {
  files: File[];
}

export interface EmptyResponse {
}

export const FILE_PACKAGE_NAME = "file";
