// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: file/file.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { DeleteFileRequest, UploadFileRequest } from "./file.command.pb.js";
import { GetFileRequest, GetUserFilesRequest } from "./file.query.pb.js";
import { EmptyResponse, FileListResponse, FileResponse } from "./file.responses.pb.js";

export const protobufPackage = "file";

export const FILE_PACKAGE_NAME = "file";

export interface FileServiceClient {
  uploadFile(request: Observable<UploadFileRequest>): Observable<FileResponse>;

  getFile(request: GetFileRequest): Observable<FileResponse>;

  getUserFiles(request: GetUserFilesRequest): Observable<FileListResponse>;

  deleteFile(request: DeleteFileRequest): Observable<EmptyResponse>;
}

export interface FileServiceController {
  uploadFile(request: Observable<UploadFileRequest>): Promise<FileResponse> | Observable<FileResponse> | FileResponse;

  getFile(request: GetFileRequest): Promise<FileResponse> | Observable<FileResponse> | FileResponse;

  getUserFiles(
    request: GetUserFilesRequest,
  ): Promise<FileListResponse> | Observable<FileListResponse> | FileListResponse;

  deleteFile(request: DeleteFileRequest): Promise<EmptyResponse> | Observable<EmptyResponse> | EmptyResponse;
}

export function FileServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getFile", "getUserFiles", "deleteFile"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FileService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["uploadFile"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FileService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FILE_SERVICE_NAME = "FileService";
