// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: file/file.proto

/* eslint-disable */

export const protobufPackage = "file";

export interface File {
  id: string;
  userId: string;
  originalName: string;
  minioKey: string;
  mimeType: string;
  size: number;
}

export const FILE_PACKAGE_NAME = "file";
