// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: file/file.command.proto

/* eslint-disable */

export const protobufPackage = "file";

export interface UploadFileRequest {
  metadata?: UploadMetadata | undefined;
  chunk?: Uint8Array | undefined;
}

export interface UploadMetadata {
  userId: string;
  originalName: string;
  mimeType: string;
  size: number;
}

export interface DeleteFileRequest {
  id: string;
}

export const FILE_PACKAGE_NAME = "file";
