// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: file/file.query.proto

/* eslint-disable */

export const protobufPackage = "file";

export interface GetFileRequest {
  id: string;
}

export interface GetUserFilesRequest {
  userId: string;
}

export const FILE_PACKAGE_NAME = "file";
