// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: user/user.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { DeleteUserRequest, RegisterRequest } from "./user.command.pb.js";
import { GetUserRequest, LoginRequest, VerifyTokenRequest } from "./user.query.pb.js";
import { EmptyResponse, TokenResponse, UserResponse, VerifyTokenResponse } from "./user.responses.pb.js";

export const protobufPackage = "user";

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  register(request: RegisterRequest): Observable<TokenResponse>;

  login(request: LoginRequest): Observable<TokenResponse>;

  verifyToken(request: VerifyTokenRequest): Observable<VerifyTokenResponse>;

  getUser(request: GetUserRequest): Observable<UserResponse>;

  deleteUser(request: DeleteUserRequest): Observable<EmptyResponse>;
}

export interface UserServiceController {
  register(request: RegisterRequest): Promise<TokenResponse> | Observable<TokenResponse> | TokenResponse;

  login(request: LoginRequest): Promise<TokenResponse> | Observable<TokenResponse> | TokenResponse;

  verifyToken(
    request: VerifyTokenRequest,
  ): Promise<VerifyTokenResponse> | Observable<VerifyTokenResponse> | VerifyTokenResponse;

  getUser(request: GetUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  deleteUser(request: DeleteUserRequest): Promise<EmptyResponse> | Observable<EmptyResponse> | EmptyResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["register", "login", "verifyToken", "getUser", "deleteUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
