// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: user/user.query.proto

/* eslint-disable */

export const protobufPackage = "user";

export interface LoginRequest {
  email: string;
  password: string;
}

export interface GetUserRequest {
  id: string;
}

export interface VerifyTokenRequest {
  token: string;
}

export const USER_PACKAGE_NAME = "user";
