// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: user/user.responses.proto

/* eslint-disable */
import { User } from "./user.pb.js";

export const protobufPackage = "user";

export interface TokenResponse {
  accessToken: string;
  expiresIn: number;
}

export interface UserResponse {
  user: User | undefined;
}

export interface EmptyResponse {
}

export const USER_PACKAGE_NAME = "user";
