// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: account/account.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  CreateTransactionRequest,
  ListTransactionsRequest,
  ListTransactionsResponse,
  TransactionResponse,
} from "./account.query.pb.js";

export const protobufPackage = "account";

export const ACCOUNT_PACKAGE_NAME = "account";

export interface AccountServiceClient {
  createTransaction(request: CreateTransactionRequest): Observable<TransactionResponse>;

  getTransactions(request: ListTransactionsRequest): Observable<ListTransactionsResponse>;
}

export interface AccountServiceController {
  createTransaction(
    request: CreateTransactionRequest,
  ): Promise<TransactionResponse> | Observable<TransactionResponse> | TransactionResponse;

  getTransactions(
    request: ListTransactionsRequest,
  ): Promise<ListTransactionsResponse> | Observable<ListTransactionsResponse> | ListTransactionsResponse;
}

export function AccountServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createTransaction", "getTransactions"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AccountService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AccountService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ACCOUNT_SERVICE_NAME = "AccountService";
