// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: account/account.proto

/* eslint-disable */

export const protobufPackage = "account";

export enum EventTag {
  FOOD = 0,
  TRANSPORT = 1,
  ENTERTAINMENT = 2,
  SHOPPING = 3,
  HEALTH = 4,
  TRAVEL = 5,
  UTILITIES = 6,
  OTHER = 7,
  UNRECOGNIZED = -1,
}

export interface Transaction {
  id: string;
  name: string;
  price: number;
  tag: EventTag;
  userId: string;
  createdAt: string;
}

export const ACCOUNT_PACKAGE_NAME = "account";
