// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.3
// source: account/account.query.proto

/* eslint-disable */
import { EventTag } from "./account.pb.js";

export const protobufPackage = "account";

export interface CreateTransactionRequest {
  name: string;
  price: number;
  tag: EventTag;
  userId: string;
  address: string;
}

export interface TransactionResponse {
  id: string;
  name: string;
  price: number;
  tag: EventTag;
  userId: string;
  createdAt: string;
}

export interface ListTransactionsRequest {
  userId: string;
}

export interface ListTransactionsResponse {
  transactions: TransactionResponse[];
}

export const ACCOUNT_PACKAGE_NAME = "account";
